<x-dashboard.top-nav>
    <x-dashboard.nav-item
        title="Borrowings"
        uri="/borrowings"
    />
    <x-dashboard.nav-item
        title="History"
        uri='/borrowings-history'
    />
</x-dashboard.top-nav>
